PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX v: <http://www.wikidata.org/prop/statement/>
PREFIX q: <http://www.wikidata.org/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?name ?hubAirportCode WHERE {
  ?airline wdt:P229 ?code .  
  FILTER(lcase(?code) = lcase("{{airline_code}}")) .
  ?airline wdt:P113 ?hubAirport .
  ?hubAirport wdt:P238 ?hubAirportCode .
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en" .
    ?airline rdfs:label ?name .
  }
} LIMIT 20
